tap "homebrew/dupes"

brew "coreutils"
brew "ffmpeg"
brew "git"
brew "grc"
brew "hub"
brew "node"
brew "postgres"
brew "python"
brew "rbenv"
brew "redis"
brew "ruby-build"
brew "xcproj"
brew "xctool"
brew "z"
brew "zsh-completions"

tap "caskroom/versions"

# cask "iterm2"
cask "virtualbox"
cask "vagrant"

# Fonts
tap "caskroom/fonts"

cask "font-inconsolata-dz"
cask "font-inconsolata-dz-for-powerline"
cask "font-inconsolata-for-powerline"
cask "font-inconsolata-g-for-powerline"
cask "font-meslo-lg"
cask "font-meslo-for-powerline"
cask "font-montserrat"
cask "font-open-sans"
cask "font-source-code-pro"
cask "font-yanone-kaffeesatz"

mas "Xcode", id: 497799835
mas "Redacted", id: 984968384
mas "Irvue", id: 1039633667
mas "Pastebot", id: 1179623856
mas "Spark", id: 1176895641
mas "Xcode", id: 497799835
mas "Tweetbot", id: 557168941

# thoughtbot
tap "thoughtbot/formulae"
brew "liftoff"

