# Taps
tap 'homebrew/core'
tap 'homebrew/boneyard'
tap 'homebrew/bundle'
tap 'homebrew/services'
tap 'getsentry/tools'
tap 'lyft/formulae'
tap 'facebook/fb'
tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'kylef/formulae'
tap 'neovim/neovim'
tap 'tomanthony/brews'

# Casks
cask_args appdir: '/Applications'
cask 'java8'
cask 'virtualbox'
cask 'vagrant'

# Brews
brew 'autoconf'
brew 'automake'
brew 'awscli'
brew 'carthage'
brew 'cmake'
brew 'coreutils'
brew 'ctop'
brew 'curl'
brew 'elasticsearch@5.6', restart_service: true
brew 'elm'
brew 'ffmpeg', args: ['with-fontconfig', 'with-libass']
brew 'flow'
brew 'gdb'
brew 'gettext'
brew 'git-lfs'
brew 'git'
brew 'grc'
brew 'highlight'
brew 'hub'
brew 'imagemagick', args: ['with-fontconfig']
brew 'infer'
brew 'ios-sim'
brew 'jq'
brew 'leiningen'
brew 'libtermkey'
brew 'libtool'
brew 'libuv'
brew 'libvterm'
brew 'mas'
brew 'mosh'
brew 'msgpack'
brew 'neovim'
brew 'node'
brew 'nvm'
brew 'openssl'
brew 'pandoc'
brew 'postgresql', restart_service: true
brew 'rbenv'
brew 'readline'
brew 'redis'
brew 'rlwrap'
brew 'ruby-build'
brew 'smlnj'
brew 'sourcekitten'
brew 'stunnel'
brew 'swiftlint'
brew 'tig'
brew 'tree'
brew 'watchman'
brew 'wget'
brew 'xcproj'
brew 'xctool'
brew 'xz'
brew 'yarn'
brew 'z'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'
brew 'zsh'
brew 'getsentry/tools/sentry-cli'
brew 'kylef/formulae/swiftenv'
brew 'lyft/formulae/set-simulator-location'
brew 'tomanthony/brews/itermocil'

# Fonts
cask 'font-inconsolata-dz'
cask 'font-inconsolata-dz-for-powerline'
cask 'font-inconsolata-for-powerline'
cask 'font-inconsolata-g-for-powerline'
cask 'font-meslo-lg'
cask 'font-meslo-for-powerline'
cask 'font-montserrat'
cask 'font-open-sans'
cask 'font-source-code-pro'
cask 'font-yanone-kaffeesatz'
cask 'font-fira-mono-for-powerline'
cask 'font-fira-mono'
cask 'font-fira-code'
cask 'font-hasklig'

# App Store apps
mas 'Blackmagic Disk Speed Test', id: 425264550
mas 'Calcbot', id: 931657367
mas 'Deckset', id: 847496013
mas 'Deliveries', id: 924726344
mas 'Irvue', id: 1039633667
mas 'Pastebot', id: 1179623856
mas 'Radium', id: 597611879
mas 'Redacted', id: 984968384
mas 'Spark', id: 1176895641
mas 'The Unarchiver', id: 425424353
mas 'Tweetbot', id: 557168941
mas 'Xcode', id: 497799835
