#!/bin/sh
# Run by github/github codespaces after starting

# Always want to use ZSH as my default shell (e.g. for SSH)
if ! grep -q "root.*/bin/zsh" /etc/passwd
then
  chsh -s /bin/zsh root
fi

# Configure Linuxbrew if installed
test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
test -r ~/.bash_profile && echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >> ~/.bash_profile
echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >> ~/.profile

# Install some developer tools and setup Linux how I like it
apt install -y \
  exa grc ripgrep shellcheck locate zoxide bat \
  fd-find duf

# Delta isn't on aptitude, so we'll install it with Homebrew/Linuxbrew
if test "$(which brew)"; then
  brew install git-delta
fi

# Setup the database for locate
updatedb