#!/bin/sh
# Run by github/github codespaces after starting

# Always want to use ZSH as my default shell (e.g. for SSH)
sudo chsh "$(id -un)" --shell "/usr/bin/zsh"

# Install some developer tools and setup Linux how I like it
sudo apt-get update && sudo apt-get install -y \
  bat \
  fd-find \
  fzf \
  grc \
  neovim \
  ripgrep \
  shellcheck

# linux workaround for bat: https://github.com/sharkdp/bat?tab=readme-ov-file#on-ubuntu-using-apt
if [ -x "$(command -v batcat)" ]; then
  mkdir -p ~/.local/bin
  ln -s /usr/bin/batcat ~/.local/bin/bat
fi

# install tools via cargo if cargo is installed
if [ -x "$(command -v cargo)" ]; then
  cargo install lsd \
    zoxide \
    git-delta
fi
