#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname "$0")"/..

# find the installers and run them iteratively
find . -mindepth 2 -name install.sh | while read -r installer ; do sh -c "${installer}" ; done
